version: '3.7'

services:
  traefik:
    image: library/traefik
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--api.insecure=true'
      - '--log.level=DEBUG'
      - '--accessLog.bufferingSize=0'
      - '--entryPoints.web.address=:80'
      - '--entryPoints.websecure.address=:443'
      - '--providers.providersThrottleDuration=2s'
      - '--providers.docker=true'
      - '--providers.docker.watch=true'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.swarmMode=true'
      - '--providers.docker.swarmModeRefreshSeconds=15s'
      - '--providers.docker.exposedbydefault=false'
      - '--providers.docker.network=proxy'
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    deploy:
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=proxy'
        - 'traefik.http.routers.traefik-http.entrypoints=web'
        - 'traefik.http.services.traefik-http.loadbalancer.server.port=8080'
        - 'traefik.http.routers.traefik-https.rule=Host(`traefik.replaceme.nip.io`)'
networks:
  proxy:
    external: true

