version: '3.7'
services:
  grafana:
    image: grafana/grafana
    networks:
     - monitoring
     - proxy
    volumes:
      - /srv/docker/monitor/volumes/grafana:/var/lib/grafana
    deploy:
      labels:
        - 'traefik.enable=true'
        - 'traefik.docker.network=proxy'
        - 'traefik.http.routers.grafana-http.entrypoints=web'
        - 'traefik.http.services.grafana-http.loadbalancer.server.port=3000'
        - 'traefik.http.routers.grafana-https.rule=Host(`grafana.replaceme.nip.io`)'
  influxdb:
    image: influxdb
    configs:
      - source: influxdb
        target: /etc/influxdb/influxdb.conf
    volumes:
      - /srv/docker/monitor/volumes/influxdb:/var/lib/influxdb
    networks:
     - monitoring
    environment:
      - INFLUXDB_DB=telegraf
      - INFLUXDB_USER=telegraf
      - INFLUXDB_ADMIN_ENABLED=true

      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=password 

  telegraf:
    image: telegraf
    hostname: "{{.Node.Hostname}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf
        target: /etc/telegraf/telegraf.conf
    networks:
     - monitoring
    deploy:
      mode: global

networks:
  monitoring:
  proxy: 
    external: true

configs:
  telegraf:
    file: ./telegraf.conf
  influxdb:
    file: ./influxdb.conf

